include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - use_key_in_widget_constructors
    - cancel_subscriptions
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"